### ISSUE TITLE
Gem is breaking rails server

### ISSUE THREAD

**Issue by topherreynoso** [beamtech/beam-platform-gem#1]
After adding gem 'beam-platform' and doing a "bundle install" I get the following error when I attempt to run the rails server.

bin/rails:6: warning: already initialized constant APP_PATH
/home/ubuntu/workspace/bin/rails:6: warning: previous definition of APP_PATH was here
Error: Command '-p' not recognized

**Comment by patrickread** [comment]
Hey Topher,

What version of Rails are you on?

I wasn't able to reproduce that error, but I believe it's likely due to our use of `activesupport` in the gem. I just put out a version of the gem (0.0.3) which does not specify the `activesupport` version.

It seemed to work on a new test Rails app. I tried 4.1.4 as well as 4.2.6.

Can you let me know if works better at this point?

**Comment by topherreynoso** [comment]
Interesting I updated the gem and verified that it's on 0.0.3 and I got the same result. Rails 4.2.2 , so that shouldn't be the issue.

**Comment by topherreynoso** [comment]
Based on a suggestion [here](http://stackoverflow.com/questions/23402820/rails-server-bin-rails6-warning-already-initialized-constant-app-path-error), I tried rake rails:update:bin and got the following (also to be clear server runs great as soon as I remove gem 'beam-platform' and rake rails:update:bin runs just fine as well without it):

rake aborted!
LoadError: cannot load such file -- HTTParty
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/beam-platform-0.0.3/lib/beam/platform/auth.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/beam-platform-0.0.3/lib/beam/platform/api.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/beam-platform-0.0.3/lib/beam/platform.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:85:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:85:in `rescue in block in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:68:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:134:in `require'
/home/ubuntu/workspace/config/application.rb:8:in `<top (required)>'
/home/ubuntu/workspace/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- beam-platform
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:134:in `require'
/home/ubuntu/workspace/config/application.rb:8:in `<top (required)>'
/home/ubuntu/workspace/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by topherreynoso** [comment]
Looks to me like there's something up with your dependencies.

**Comment by patrickread** [comment]
Yes, that's interesting. I wonder why HTTParty won't load. Does `gem install httparty` not work?

**Comment by patrickread** [comment]
Case sensitivity in the requirement statement might be making the difference here. (https://github.com/jnunemaker/httparty/issues/241) Maybe it's an Ubuntu/OS X difference. I pushed out a new version to test that 0.0.4. https://rubygems.org/gems/beam-platform Thanks for being patient on this!

**Comment by topherreynoso** [comment]
No that works, I get their install message:

When you HTTParty, you must party hard!
Successfully installed httparty-0.13.7
1 gem installed

But still no change.

**Comment by topherreynoso** [comment]
0.0.4 is a success! That got it, thanks.

**Comment by patrickread** [comment]
Great! I'll try to keep an eye on this project's functionality on an Ubuntu machine in case other things crop up.
